import type { Metadata } from 'next';
import Providers from '@/components/providers/Provider'
import './globals.css';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className="bg-slate-800">{children}</body>
      </html>
    </Providers>
  );
}
